name: Deploy to GH Pages

on:
  push:
      branches:
        - master

jobs:
  deploy:
      runs-on: ubuntu-22.04

      strategy:
        matrix:
            node-version: [16.15.x]
      
      steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: use node js v${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: move to web directory
        uses: cd examples/id_recognition_web
      
      - name: install dependencies
        uses: npm ci
      
      - name: build project
        run: npm run build
      
      - name: deploy web
        uses: JamesIves/github-pages-deploy-action
        with:
          branch: gh-pages
          folder: dist